server:
  port: 8080
  error:
    include-stacktrace: never
  servlet:
    contextPath: /bugout/api

spring:
  application:
    name: bugout
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:./data
    username: bugout
    password: bugout
  sql:
    init:
      mode: always
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        format_sql: false
        jdbc:
          time_zone: UTC
    hibernate:
      ddl-auto: create-drop

  h2:
    console:
      enabled: true
